/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.view;

import com.mycompany.conexao.SQLiteConnector;
import com.mycompany.controlador.DisciplinaController;
import com.mycompany.model.classes.Disciplina;
import com.mycompany.model.dao.DisciplinaDAOBanco;
import com.mycompany.model.dao.IDao;
import com.mycompany.view.tables.TMCadDisciplina;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author arthur
 */
public class jDialogDisciplina extends javax.swing.JDialog {
    
    private boolean editando;
    private String codAntigo;
    private DisciplinaController disciplinaController;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jDialogDisciplina.class.getName());

    
    
    public jDialogDisciplina(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        initComponents();
        this.editando = false;
         this.codAntigo = "";
         
         
        SQLiteConnector conexao = new SQLiteConnector("banco.sqlite");
        IDao disciplinaDao = new DisciplinaDAOBanco(conexao.getConnection());
        this.disciplinaController = new DisciplinaController(disciplinaDao);
         
        initComponents();
        setLocationRelativeTo(parent);
        

        this.habilitarCampos(false);
        this.limparCampos();
        this.atualizarTabela();
    }
    public void habilitarCampos(boolean flag) {
        edtCod.setEnabled(flag);
        edtNome.setEnabled(flag);
        edtSemestre.setEnabled(flag);
        edtHorario.setEnabled(flag);
    }
      public void limparCampos() {
        edtCod.setText("");
        edtNome.setText("");
        edtSemestre.setText("");
        edtHorario.setText("");
    }
        public void atualizarTabela() {
        List<Disciplina> lista = this.disciplinaController.listarDisciplinas();
        TMCadDisciplina tmcadisciplina = new TMCadDisciplina(lista);
        grdDisciplina.setModel(tmcadisciplina);
    }
        public void objetoParaCampos(Disciplina p) {
      edtCod.setText(p.getCod());
       edtNome.setText(p.getNome());
       edtSemestre.setText(p.getSemestre()+ "");
       edtHorario.setText(p.getHorario());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNovo6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnEditar = new javax.swing.JButton();
        btnNovo1 = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnMatricular = new javax.swing.JButton();
        btnMatricularProf = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtCod = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        edtNome = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        edtHorario = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        edtSemestre = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        grdDisciplina = new javax.swing.JTable();

        btnNovo6.setText("Matricula aluno");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Noto Sans Nerd Font", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Disciplina");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar);

        btnNovo1.setText("Novo");
        btnNovo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovo1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnNovo1);

        btnExcluir.setText("Excluir");
        jPanel1.add(btnExcluir);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvar);

        btnMatricular.setText("Matricula aluno");
        btnMatricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatricularActionPerformed(evt);
            }
        });
        jPanel1.add(btnMatricular);

        btnMatricularProf.setText("Professor da disciplina");
        jPanel1.add(btnMatricularProf);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("Cod: ");
        jPanel2.add(jLabel2);

        jScrollPane1.setViewportView(edtCod);

        jPanel2.add(jScrollPane1);

        jLabel3.setText("Nome:");
        jPanel2.add(jLabel3);

        jScrollPane2.setViewportView(edtNome);

        jPanel2.add(jScrollPane2);

        jLabel4.setText("Hora: ");
        jPanel2.add(jLabel4);

        jScrollPane3.setViewportView(edtHorario);

        jPanel2.add(jScrollPane3);

        jLabel5.setText("Periodo:");
        jPanel2.add(jLabel5);

        jScrollPane4.setViewportView(edtSemestre);

        jPanel2.add(jScrollPane4);

        grdDisciplina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(grdDisciplina);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovo1ActionPerformed
        this.limparCampos();
      this.habilitarCampos(true);
      this.editando = false;
    }//GEN-LAST:event_btnNovo1ActionPerformed
   
     
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        Disciplina disciplinaEscolhida = this.getObjetoSelecionadoNaGrid();
       
       String codEscolhido = disciplinaEscolhida.getCod();

        Disciplina disciplinaEditando = disciplinaController.buscarDisciplina(codEscolhido);

        if (disciplinaEditando == null) {
            JOptionPane.showMessageDialog(this, "Disciplina não existe na escola");
            this.editando = false;
        } else {
            this.limparCampos();
            this.habilitarCampos(true);
            
            this.objetoParaCampos(disciplinaEditando);
            this.editando = true;
            this.codAntigo = disciplinaEditando.getCod();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.limparCampos();
        this.habilitarCampos(false);
        this.editando = false;
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
         if (this.editando == true) {
            this.disciplinaController.atualizarDisciplina(codAntigo, edtNome.getText(), edtSemestre.getText(), edtHorario.getText());
        } else {
            this.disciplinaController.adicionarDisciplina(edtCod.getText(), edtNome.getText(), edtSemestre.getText(), edtHorario.getText());
        }

        this.limparCampos();
        this.habilitarCampos(false);

        this.atualizarTabela();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatricularActionPerformed
    Disciplina disciplinaEscolhida = this.getObjetoSelecionadoNaGrid();

    if (disciplinaEscolhida == null) {
        JOptionPane.showMessageDialog(this, "Disciplina não existe na escola");
    } else {
        JDialogSelectALuno tela = null;
        try {
            // Obtém o frame pai da janela atual e passa para o diálogo
            java.awt.Frame framePai = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
            tela = new JDialogSelectALuno(framePai, true, disciplinaEscolhida);
        } catch (SQLException ex) {
            Logger.getLogger(JDialogSelectProfessor.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (tela != null) {
            tela.setVisible(true);
        }
        atualizarTabela();
    }
    }//GEN-LAST:event_btnMatricularActionPerformed
     private void grdAlunoMouseClicked(java.awt.event.MouseEvent evt) {                                       
       Disciplina a = this.getObjetoSelecionadoNaGrid();
       this.objetoParaCampos(a);
    }
    public Disciplina getObjetoSelecionadoNaGrid() {
        int linhaSelecionada = grdDisciplina.getSelectedRow();

        if (linhaSelecionada >= 0) {
            TMCadDisciplina tmCadAluno = (TMCadDisciplina) grdDisciplina.getModel();

             Disciplina d = tmCadAluno.getObjetoAluno(linhaSelecionada);
            return d;
        }
        
        return null;
    }
      
    
  
    
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnMatricular;
    private javax.swing.JButton btnMatricularProf;
    private javax.swing.JButton btnNovo1;
    private javax.swing.JButton btnNovo6;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextPane edtCod;
    private javax.swing.JTextPane edtHorario;
    private javax.swing.JTextPane edtNome;
    private javax.swing.JTextPane edtSemestre;
    private javax.swing.JTable grdDisciplina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
