/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.view;

import com.mycompany.conexao.SQLiteConnector;
import com.mycompany.controlador.AlunoController;
import com.mycompany.model.classes.Aluno;
import com.mycompany.model.dao.AlunoDAOBanco;
import com.mycompany.model.dao.IDao;
import com.mycompany.view.tables.TMCadAluno;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author arthur
 */
public class JDialogAluno extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogAluno.class.getName());

    private boolean editando;
    private String cpfAntigo;
    private AlunoController alunoController;
    
    public JDialogAluno(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        initComponents();
    this.editando = false;
    this.cpfAntigo = "";
    SQLiteConnector conexao = new SQLiteConnector("banco.sqlite");
    IDao alunoDao = new AlunoDAOBanco(conexao.getConnection());
     this.alunoController = new AlunoController(alunoDao);
     
     setLocationRelativeTo(parent);
      initData();
    
        
    }
     public void habilitarCampos(boolean flag) {
        edtCpf.setEnabled(flag);
        edtMatricula.setEnabled(flag);
        edtNome.setEnabled(flag);
        edtIdade.setEnabled(flag);
        edtAnoIngresso.setEnabled(flag);
    }
     private void initData() {
    this.habilitarCampos(false);
    this.limparCampos();

    this.atualizarTabela();
}
     public void limparCampos() {
        edtCpf.setText("");
        edtMatricula.setText("");
        edtNome.setText("");
        edtIdade.setText("");
        edtAnoIngresso.setText("");
    }
      public void objetoParaCampos(Aluno a) {
       edtCpf.setText(a.getCpf());
       edtMatricula.setText(a.getMatricula());
       edtNome.setText(a.getNome());
       edtIdade.setText(a.getIdade() + "");
       edtAnoIngresso.setText(a.getAnoIngresso()+ "");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEditar1 = new javax.swing.JButton();
        lblAluno = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEditar2 = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        edtNome = new javax.swing.JTextPane();
        lblNome1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtCpf = new javax.swing.JTextPane();
        lblNome2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        edtMatricula = new javax.swing.JTextPane();
        lblNome4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        edtAnoIngresso = new javax.swing.JTextPane();
        lblNome3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        edtIdade = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        grdAluno = new javax.swing.JTable();

        btnEditar1.setText("Editar");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblAluno.setBackground(new java.awt.Color(204, 204, 204));
        lblAluno.setFont(new java.awt.Font("Noto Sans Nerd Font", 3, 18)); // NOI18N
        lblAluno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAluno.setText("Aluno");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNovo);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar);

        btnEditar2.setText("Editar");
        btnEditar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar2);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvar);

        btnExcluir1.setText("Excluir");
        btnExcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluir1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnExcluir1);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setForeground(new java.awt.Color(102, 102, 102));

        lblNome.setText("Nome: ");
        jPanel3.add(lblNome);

        jScrollPane2.setViewportView(edtNome);

        jPanel3.add(jScrollPane2);

        lblNome1.setText("CPF:");
        jPanel3.add(lblNome1);

        jScrollPane1.setViewportView(edtCpf);

        jPanel3.add(jScrollPane1);

        lblNome2.setText("Matricula: ");
        jPanel3.add(lblNome2);

        jScrollPane3.setViewportView(edtMatricula);

        jPanel3.add(jScrollPane3);

        lblNome4.setText("Ano de Ingresso: ");
        jPanel3.add(lblNome4);

        jScrollPane4.setViewportView(edtAnoIngresso);

        jPanel3.add(jScrollPane4);

        lblNome3.setText("Idade: ");
        jPanel3.add(lblNome3);

        jScrollPane5.setViewportView(edtIdade);

        jPanel3.add(jScrollPane5);

        grdAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(grdAluno);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane6)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar2ActionPerformed
        Aluno alunoEscolhido = this.getObjetoSelecionadoNaGrid();
       
       String CPFEscolhido = alunoEscolhido.getCpf();

        Aluno alunoEditando = alunoController.buscarAluno(CPFEscolhido);

        if (alunoEditando == null) {
            JOptionPane.showMessageDialog(this, "Não existe aluno com o  cpf escolhido ");
            this.editando = false;
        } else {
            this.limparCampos();
            this.habilitarCampos(true);
            
            this.objetoParaCampos(alunoEditando);
            this.editando = true;
            this.cpfAntigo = alunoEditando.getCpf();
        }

    }//GEN-LAST:event_btnEditar2ActionPerformed
      public Aluno getObjetoSelecionadoNaGrid() {
        int linhaSelecionada = grdAluno.getSelectedRow();

        if (linhaSelecionada >= 0) {
            TMCadAluno tmCadAluno = (TMCadAluno) grdAluno.getModel();

             Aluno aluno = tmCadAluno.getObjetoAluno(linhaSelecionada);
            return aluno;
        }
        
        return null;
    }
       public void atualizarTabela() {
        List<Aluno> lista = this.alunoController.listarAlunos();
        TMCadAluno tmcadaluno = new TMCadAluno(lista);
        grdAluno.setModel(tmcadaluno);
    }
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Aluno novoAluno = alunoController.buscarAluno(edtCpf.getText());
        if (this.editando == true) {
            if(cpfAntigo == null ? edtCpf.getText() == null : cpfAntigo.equals(edtCpf.getText()))
                this.alunoController.atualizarAluno(cpfAntigo,edtCpf.getText(), edtNome.getText(), edtIdade.getText(), edtMatricula.getText(), edtAnoIngresso.getText());
            else if(novoAluno == null)
                this.alunoController.atualizarAluno(cpfAntigo,edtCpf.getText(), edtNome.getText(), edtIdade.getText(), edtMatricula.getText(), edtAnoIngresso.getText());
            else 
                JOptionPane.showMessageDialog(this, "Um aluno possui esse cpf ");
        } else { 
            
                if(novoAluno == null){
                this.alunoController.adicionarAluno(edtCpf.getText(), edtNome.getText(), edtIdade.getText(), edtMatricula.getText(), edtAnoIngresso.getText());
            } else {
                JOptionPane.showMessageDialog(this, " Um aluno possui esse cpf ");
            }
        }

        this.limparCampos();
        this.habilitarCampos(false);
        this.editando = false;

        this.atualizarTabela();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluir1ActionPerformed
         Aluno alunoExcluido = this.getObjetoSelecionadoNaGrid();
        
        String cpfEscolhido = alunoExcluido.getCpf();
        
        Aluno a = alunoController.buscarAluno(cpfEscolhido);

        if (a == null) {
            JOptionPane.showMessageDialog(this, "Não existe aluno com este CPF.");
        } else {
            this.alunoController.removerAluno(cpfEscolhido);
            JOptionPane.showMessageDialog(this, "Exclusão feita com sucesso!");
        }

        this.atualizarTabela();
    }//GEN-LAST:event_btnExcluir1ActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        this.habilitarCampos(true);
        this.limparCampos();
        this.editando = false;
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.limparCampos();
        this.habilitarCampos(false);
        this.editando = false;
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar1;
    private javax.swing.JButton btnEditar2;
    private javax.swing.JButton btnExcluir1;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextPane edtAnoIngresso;
    private javax.swing.JTextPane edtCpf;
    private javax.swing.JTextPane edtIdade;
    private javax.swing.JTextPane edtMatricula;
    private javax.swing.JTextPane edtNome;
    private javax.swing.JTable grdAluno;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblAluno;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblNome2;
    private javax.swing.JLabel lblNome3;
    private javax.swing.JLabel lblNome4;
    // End of variables declaration//GEN-END:variables
}
