/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.view;

import com.mycompany.conexao.SQLiteConnector;
import com.mycompany.controlador.DisciplinaController;
import com.mycompany.model.classes.Disciplina;
import com.mycompany.model.dao.DisciplinaDAOBanco;
import com.mycompany.model.dao.IDao;
import com.mycompany.view.JDialogSelectProfessor;
import com.mycompany.view.tables.TMCadDisciplina;
import java.awt.Frame;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author arthur
 */
public class JDialogDisciplina extends javax.swing.JDialog {
    
    private boolean editando;
    private String codAntigo;
    private DisciplinaController disciplinaController;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogDisciplina.class.getName());

    
    
    public JDialogDisciplina(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        initComponents();
        this.editando = false;
         this.codAntigo = "";
         
         
        SQLiteConnector conexao = new SQLiteConnector("banco.sqlite");
        IDao disciplinaDao = new DisciplinaDAOBanco(conexao.getConnection());
        this.disciplinaController = new DisciplinaController(disciplinaDao);
         
        initComponents();
        setLocationRelativeTo(parent);
        

        this.habilitarCampos(false);
        this.limparCampos();
        this.atualizarTabela();
    }
    public void habilitarCampos(boolean flag) {
        edtCod.setEnabled(flag);
        edtNome.setEnabled(flag);
        edtSemestre.setEnabled(flag);
        edtHorario.setEnabled(flag);
    }
      public void limparCampos() {
        edtCod.setText("");
        edtNome.setText("");
        edtSemestre.setText("");
        edtHorario.setText("");
    }
        public void atualizarTabela() {
        List<Disciplina> lista = this.disciplinaController.listarDisciplinas();
        TMCadDisciplina tmcadisciplina = new TMCadDisciplina(lista);
        grdDisciplina.setModel(tmcadisciplina);
    }
        public void objetoParaCampos(Disciplina p) {
        edtCod.setText(p.getCod());
       edtNome.setText(p.getNome());
       edtSemestre.setText(p.getSemestre()+ "");
       edtHorario.setText(p.getHorario());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNovo6 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnEditar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnMatricular = new javax.swing.JButton();
        btnMatricularProf = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        edtCod = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        edtNome = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        edtSemestre = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        edtHorario = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        grdDisciplina = new javax.swing.JTable();

        btnNovo6.setText("Matricula aluno");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Noto Sans Nerd Font", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Disciplina");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar);

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNovo);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btnExcluir);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvar);

        btnMatricular.setText("Matricula aluno");
        btnMatricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatricularActionPerformed(evt);
            }
        });
        jPanel1.add(btnMatricular);

        btnMatricularProf.setText("Professor da disciplina");
        btnMatricularProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatricularProfActionPerformed(evt);
            }
        });
        jPanel1.add(btnMatricularProf);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cod: ");

        edtCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCodActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome:");

        jScrollPane2.setViewportView(edtNome);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hora: ");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Periodo:");

        jScrollPane4.setViewportView(edtSemestre);

        jScrollPane3.setViewportView(edtHorario);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel5))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(edtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        grdDisciplina.setBackground(new java.awt.Color(51, 51, 51));
        grdDisciplina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(grdDisciplina);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        this.limparCampos();
      this.habilitarCampos(true);
      this.editando = false;
    }//GEN-LAST:event_btnNovoActionPerformed
   
     
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        Disciplina disciplinaEscolhida = this.getObjetoSelecionadoNaGrid();
       
       String codEscolhido = disciplinaEscolhida.getCod();

        Disciplina disciplinaEditando = disciplinaController.buscarDisciplina(codEscolhido);

        if (disciplinaEditando == null) {
            JOptionPane.showMessageDialog(this, "Disciplina não existe na escola");
            this.editando = false;
        } else {
            this.limparCampos();
            this.habilitarCampos(true);
            
            this.objetoParaCampos(disciplinaEditando);
            this.editando = true;
            this.codAntigo = disciplinaEditando.getCod();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.limparCampos();
        this.habilitarCampos(false);
        this.editando = false;
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
    String cod = edtCod.getText().trim();
    String nome = edtNome.getText().trim();
    String semestre = edtSemestre.getText().trim();
    String horario = edtHorario.getText().trim();

    if (cod.isEmpty()) {
        JOptionPane.showMessageDialog(this, "O campo Código deve ser preenchido.", "Erro", JOptionPane.ERROR_MESSAGE);
        edtCod.requestFocus();
        return;
    }
    if (nome.isEmpty()) {
        JOptionPane.showMessageDialog(this, "O campo Nome deve ser preenchido.", "Erro", JOptionPane.ERROR_MESSAGE);
        edtNome.requestFocus();
        return;
    }
    // ... faça o mesmo para semestre e horario, se quiser validar todos

    try {
        if (this.editando) {
            this.disciplinaController.atualizarDisciplina(codAntigo, nome, semestre, horario);
        } else {
            this.disciplinaController.adicionarDisciplina(cod, nome, semestre, horario);
        }
        this.limparCampos();
        this.habilitarCampos(false);
        this.atualizarTabela();
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Erro ao salvar disciplina: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatricularActionPerformed
    Disciplina disciplinaEscolhida = this.getObjetoSelecionadoNaGrid();

    if (disciplinaEscolhida == null) {
        JOptionPane.showMessageDialog(this, "Disciplina não existe na escola");
    } else {
        JDialogSelectALuno tela = null;
        try {
            // Obtém o frame pai da janela atual e passa para o diálogo
            java.awt.Frame framePai = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
            tela = new JDialogSelectALuno(framePai, true, disciplinaEscolhida);
        } catch (SQLException ex) {
            Logger.getLogger(JDialogSelectProfessor.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (tela != null) {
            tela.setVisible(true);
        }
        atualizarTabela();
    }
    }//GEN-LAST:event_btnMatricularActionPerformed

    private void btnMatricularProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatricularProfActionPerformed
        Disciplina DisciplinaEscolhida = this.getObjetoSelecionadoNaGrid();  
    
    if (DisciplinaEscolhida == null) {
        JOptionPane.showMessageDialog(this, "Disciplina não existente na escola.");
    } else {
        JDialogSelectProfessor tela = null;
        try {
            tela = new JDialogSelectProfessor((Frame) this.getParent(), true, DisciplinaEscolhida);
        } catch (SQLException ex) {
           Logger.getLogger(JDialogDisciplina.class.getName()).log(Level.SEVERE, null, ex);
        }
        tela.setVisible(true);
        atualizarTabela();
    }
    }//GEN-LAST:event_btnMatricularProfActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        Disciplina disciplinaEscolhida = this.getObjetoSelecionadoNaGrid();

if (disciplinaEscolhida == null) {
    JOptionPane.showMessageDialog(this, "Selecione uma disciplina para excluir.");
    return;
}

String nomeEscolhido = disciplinaEscolhida.getCod();

if (nomeEscolhido == null || nomeEscolhido.trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Código da disciplina inválido.");
    return;
}

Disciplina a = disciplinaController.buscarDisciplina(nomeEscolhido);

if (a == null) {
    JOptionPane.showMessageDialog(this, "Não existe disciplina com este código.");
} else {
    disciplinaController.removerDisciplina(nomeEscolhido);
    JOptionPane.showMessageDialog(this, "Exclusão feita com sucesso!");
}

this.atualizarTabela();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void edtCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCodActionPerformed
    private void grdAlunoMouseClicked(java.awt.event.MouseEvent evt) {                                       
       Disciplina a = this.getObjetoSelecionadoNaGrid();
       this.objetoParaCampos(a);
    }
    
    public Disciplina getObjetoSelecionadoNaGrid() {
        int linhaSelecionada = grdDisciplina.getSelectedRow();

        if (linhaSelecionada >= 0) {
            TMCadDisciplina tmCadAluno = (TMCadDisciplina) grdDisciplina.getModel();

             Disciplina d = tmCadAluno.getObjetoAluno(linhaSelecionada);
            return d;
        }
        
        return null;
    }
     
  
      
    
  
    
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnMatricular;
    private javax.swing.JButton btnMatricularProf;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnNovo6;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField edtCod;
    private javax.swing.JTextPane edtHorario;
    private javax.swing.JTextPane edtNome;
    private javax.swing.JTextPane edtSemestre;
    private javax.swing.JTable grdDisciplina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
